[workspace]
members = ["crates/core", "crates/firmware", "crates/desktop", "crates/i18n-macros"]
default-members = ["crates/firmware"]
resolver = "2"

[profile.dev.package.esp-radio]
opt-level = 3
[profile.dev.package.esp-wifi-sys]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false
