name: Build ESP32-C3 Firmware Components

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imc-unknown-none-elf

      - name: Install esptool
        run: pip install esptool

      # Собираем чистый ELF-файл игры под архитектуру ESP32-C3
      - name: Build Firmware for ESP32-C3
        run: cargo build --release -p catode32-firmware --no-default-features --features c3 --target riscv32imc-unknown-none-elf

      # 1. Извлекаем чистый app.bin игры строго в аппаратном режиме DIO
      - name: Convert ELF to Clean App BIN
        run: |
          esptool.py --chip esp32c3 elf2image --flash_mode dio --output app.bin target/riscv32imc-unknown-none-elf/release/catode32-firmware

      # 2. Скачиваем официальный стабильный Bootloader (DIO) от разработчиков esp-hal
      - name: Download Official Bootloader
        run: |
          curl -L -o bootloader.bin https://github.com

      # 3. Скачиваем официальную таблицу разделов (NVS 24KB) от разработчиков esp-hal
      - name: Download Official Partition Table
        run: |
          curl -L -o partitions.bin https://github.com

      # 4. Упаковываем все 3 полученных файла в один архив
      - name: Upload All Components Artifact
        uses: actions/upload-artifact@v4
        with:
          name: catode32-esp32c3-separated-bins
          path: |
            app.bin
            bootloader.bin
            partitions.bin
